# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded Mycnf 1.0 [list source [file join $dir mycnf.tcl]]
package ifneeded MysqlInstaller 1.0 [list source [file join $dir mysql-installer.tcl]]
package ifneeded SecureMe 1.0 [list source [file join $dir secure-me.tcl]]
package ifneeded SqlRunner 1.0 [list source [file join $dir sql-runner.tcl]]
package ifneeded AddUser 1.0 [list source [file join $dir add-user.tcl]]
package ifneeded FreezeReplca 1.0 [list source [file join $dir freeze-replica.tcl]]
