package provide OsUtil 1.0
package require CommonUtil

namespace eval ::OsUtil {

}

proc ::OsUtil::doCommonTasks {ymlDict rawParamDict} {
  if {[dict exists $ymlDict NameServer]} {
    disableNetworkManager
    changeResolver [dict get $ymlDict NameServer]
  }
  setHostName $ymlDict
}

proc ::OsUtil::changeResolver {resolver} {
  if {! [file exists /etc/resolv.conf.origin]} {
    cp /etc/resolv.conf /etc/resolv.conf.origin
  }
  set fid [open /etc/resolv.conf w]
  puts $fid "# Generated by EasyInstaller"
  puts $fid "nameserver $resolver"
  close $fid
}

proc ::OsUtil::setHostName {ymlDict} {
  if {[dict exists $ymlDict HostName]} {
    exec hostnamectl set-hostname [dict get $ymlDict HostName] --static
  }
}

proc ::OsUtil::disableNetworkManager {} {
  catch {
    exec systemctl stop NetworkManager
    exec systemctl disable NetworkManager
  } msg o
}
