# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded AppDetecter 1.0 [list source [file join $dir app-detecter.tcl]]
package ifneeded CommonInstaller 1.0 [list source [file join $dir common-installer.tcl]]
package ifneeded CommonUtil 1.0 [list source [file join $dir common-util.tcl]]
package ifneeded PropertyUtil 1.0 [list source [file join $dir property-util.tcl]]
package ifneeded JavaInstaller 1.0 [list source [file join $dir java-installer.tcl]]
package ifneeded LauncherArgParser 1.0 [list source [file join $dir launcher-arg-parser.tcl]]
