# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded AppDetecter 1.0 [list source [file join $dir share/app-detecter.tcl]]
package ifneeded CommonInstaller 1.0 [list source [file join $dir share/common-installer.tcl]]
package ifneeded CommonUtil 1.0 [list source [file join $dir share/common-util.tcl]]
package ifneeded JavaInstaller 1.0 [list source [file join $dir share/java-installer.tcl]]
package ifneeded LauncherArgParser 1.0 [list source [file join $dir share/launcher-arg-parser.tcl]]
package ifneeded MysqlClusterInstaller 1.0 [list source [file join $dir mysql-cluster/mysql-cluster-installer.tcl]]
package ifneeded confutil 1.0 [list source [file join $dir mysql-cluster/config-util.tcl]]
package ifneeded ManageRole 1.0 [list source [file join $dir mysql-cluster/manage-role.tcl]]
package ifneeded MysqldRole 1.0 [list source [file join $dir mysql-cluster/mysqld-role.tcl]]
package ifneeded NdbdRole 1.0 [list source [file join $dir mysql-cluster/ndbd-role.tcl]]
package ifneeded ClusterMycnf 1.0 [list source [file join $dir mysql-cluster/cluster-mycnf.tcl]]
package ifneeded confini 1.0 [list source [file join $dir mysql-cluster/config-ini.tcl]]
package ifneeded Mycnf 1.0 [list source [file join $dir mysql/mycnf.tcl]]
package ifneeded MysqlInstaller 1.0 [list source [file join $dir mysql/mysql-installer.tcl]]
package ifneeded MysqlInit 1.0 [list source [file join $dir mysql/mysql-init.tcl]]
