# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded MysqlClusterInstaller 1.0 [list source [file join $dir mysql-cluster-installer.tcl]]
package ifneeded confutil 1.0 [list source [file join $dir config-util.tcl]]
package ifneeded ManageRole 1.0 [list source [file join $dir manage-role.tcl]]
package ifneeded MysqldRole 1.0 [list source [file join $dir mysqld-role.tcl]]
package ifneeded NdbdRole 1.0 [list source [file join $dir ndbd-role.tcl]]
package ifneeded ClusterMycnf 1.0 [list source [file join $dir cluster-mycnf.tcl]]
package ifneeded confini 1.0 [list source [file join $dir config-ini.tcl]]
